# Generated by Django 5.1.6 on 2026-02-12 01:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('READY', 'Ready'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired'), ('CANCELED', 'Canceled')], default='PENDING', max_length=20)),
                ('kind', models.CharField(choices=[('RAW_TABLE', 'Raw Table'), ('TAT_SUMMARY', 'Tat Summary')], default='RAW_TABLE', max_length=30)),
                ('file_format', models.CharField(choices=[('csv', 'Csv'), ('xlsx', 'Xlsx')], default='csv', max_length=10)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('row_count', models.IntegerField(default=0)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('duration_ms', models.IntegerField(default=0)),
                ('s3_bucket', models.CharField(blank=True, default='', max_length=255)),
                ('s3_key', models.CharField(blank=True, default='', max_length=1024)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
